
version: "3.9"
services:
  isaac-sim:
    image: nvcr.io/nvidia/isaac-sim:2024.1.0
    container_name: isaac-sim
    environment:
      - ACCEPT_EULA=Y
    runtime: nvidia
    networks: [rosnet]
    volumes:
      - ./workspace:/workspace/robo
    command: ["bash", "-c", "echo 'Launch Isaac Sim headless here'"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
    networks: [rosnet]

networks:
  rosnet:
    driver: bridge